# Generated by Django 4.1.3 on 2022-12-18 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='date',
            field=models.DateField(default=datetime.datetime.today, help_text='This date may be displayed on the news post.                 It is not used to schedule posts to go live at a later date.', verbose_name='Post date'),
        ),
    ]
