# Generated by Django 4.1 on 2022-09-01 01:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentpage',
            name='body',
            field=wagtail.fields.StreamField([('equipment', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Select or upload equipment image')), ('title', wagtail.blocks.CharBlock(help_text='Equipment title')), ('description', wagtail.blocks.TextBlock(help_text='Equipment description'))]))], default='', use_json_field=True),
        ),
    ]
