# Generated by Django 4.1.3 on 2022-12-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_formfield_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='hero_photo_credit',
            field=models.CharField(blank=True, help_text='80 character limit.                    This will show on the bottom right on the image', max_length=80, null=True),
        ),
    ]
