# Generated by Django 2.2.6 on 2019-11-28 18:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencepage',
            name='body',
            field=wagtail.core.fields.StreamField([('evidence', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Evidence title')), ('date', wagtail.core.blocks.DateBlock()), ('sound', wagtail.documents.blocks.DocumentChooserBlock(help_text='Select or upload evidence sound clip', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Select or upload evidence image', required=False)), ('embed', wagtail.core.blocks.StructBlock([('you_tube_embed', wagtail.core.blocks.CharBlock(help_text='Insert the embed code e.g Pha7WiAuhw4 the part that follows https://youtu.be/', required=False))], required=False))]))], default=''),
        ),
    ]
